version: "3.9"

services:
  backend:
    build: ./server
    container_name: leave_backend
    restart: always
    ports:
      - "5005:5005"
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_cmYrQ2RCzpo6@ep-gentle-dream-amh8qzcs.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require/
      JWT_SECRET: madhan
      CORS: http://localhost:5004
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: leave_frontend
    restart: always
    ports:
      - "5004:5004"
    environment:
      VITE_API_URL: http://localhost:5005/api
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  pg_data: